//
// Copyright (c) 2025 BlueCheese Games All rights reserved
//

using UnityEngine;

namespace BlueCheese.App
{
	public static class LangUtilities
	{
		public static Language GetLanguage(SystemLanguage systemLanguage) => systemLanguage switch
		{
			SystemLanguage.Afrikaans => Language.Afrikaans,
			SystemLanguage.Arabic => Language.Arabic,
			SystemLanguage.Basque => Language.Basque,
			SystemLanguage.Belarusian => Language.Belarusian,
			SystemLanguage.Bulgarian => Language.Bulgarian,
			SystemLanguage.Catalan => Language.Catalan,
			SystemLanguage.Chinese => Language.Chinese,
			SystemLanguage.Czech => Language.Czech,
			SystemLanguage.Danish => Language.Danish,
			SystemLanguage.Dutch => Language.Dutch,
			SystemLanguage.English => Language.English,
			SystemLanguage.Estonian => Language.Estonian,
			SystemLanguage.Faroese => Language.Faroese,
			SystemLanguage.Finnish => Language.Finnish,
			SystemLanguage.French => Language.French,
			SystemLanguage.German => Language.German,
			SystemLanguage.Greek => Language.Greek,
			SystemLanguage.Hebrew => Language.Hebrew,
			SystemLanguage.Hungarian => Language.Hungarian,
			SystemLanguage.Icelandic => Language.Icelandic,
			SystemLanguage.Indonesian => Language.Indonesian,
			SystemLanguage.Italian => Language.Italian,
			SystemLanguage.Japanese => Language.Japanese,
			SystemLanguage.Korean => Language.Korean,
			SystemLanguage.Latvian => Language.Latvian,
			SystemLanguage.Lithuanian => Language.Lithuanian,
			SystemLanguage.Norwegian => Language.Norwegian,
			SystemLanguage.Polish => Language.Polish,
			SystemLanguage.Portuguese => Language.Portuguese,
			SystemLanguage.Romanian => Language.Romanian,
			SystemLanguage.Russian => Language.Russian,
			SystemLanguage.SerboCroatian => Language.SerboCroatian,
			SystemLanguage.Slovak => Language.Slovak,
			SystemLanguage.Slovenian => Language.Slovenian,
			SystemLanguage.Spanish => Language.Spanish,
			SystemLanguage.Swedish => Language.Swedish,
			SystemLanguage.Thai => Language.Thai,
			SystemLanguage.Turkish => Language.Turkish,
			SystemLanguage.Ukrainian => Language.Ukrainian,
			SystemLanguage.Vietnamese => Language.Vietnamese,
			SystemLanguage.ChineseSimplified => Language.Chinese,
			SystemLanguage.ChineseTraditional => Language.Chinese,
			SystemLanguage.Hindi => Language.Hindi,
			_ => Language.Unknown,
		};

		public static Language GetLanguage(string languageCode) => languageCode switch
		{
			"en" => Language.English,
			"es" => Language.Spanish,
			"pt" => Language.Portuguese,
			"fr" => Language.French,
			"de" => Language.German,
			"it" => Language.Italian,
			"nl" => Language.Dutch,
			"ru" => Language.Russian,
			"ja" => Language.Japanese,
			"zh" => Language.Chinese,
			"ko" => Language.Korean,
			"ar" => Language.Arabic,
			"tr" => Language.Turkish,
			"no" => Language.Norwegian,
			"sv" => Language.Swedish,
			"da" => Language.Danish,
			"fi" => Language.Finnish,
			"cs" => Language.Czech,
			"hu" => Language.Hungarian,
			"pl" => Language.Polish,
			"ro" => Language.Romanian,
			"ca" => Language.Catalan,
			"el" => Language.Greek,
			"he" => Language.Hebrew,
			"id" => Language.Indonesian,
			"th" => Language.Thai,
			"vi" => Language.Vietnamese,
			"bg" => Language.Bulgarian,
			"uk" => Language.Ukrainian,
			"sk" => Language.Slovak,
			"sl" => Language.Slovenian,
			"lt" => Language.Lithuanian,
			"lv" => Language.Latvian,
			"et" => Language.Estonian,
			"af" => Language.Afrikaans,
			"eu" => Language.Basque,
			"be" => Language.Belarusian,
			"fo" => Language.Faroese,
			"is" => Language.Icelandic,
			"hr" => Language.SerboCroatian,
			_ => Language.Unknown,
		};

		public static string GetLanguageCode(Language language) => language switch
		{
			Language.English => "en",
			Language.Spanish => "es",
			Language.Portuguese => "pt",
			Language.French => "fr",
			Language.German => "de",
			Language.Italian => "it",
			Language.Dutch => "nl",
			Language.Russian => "ru",
			Language.Japanese => "ja",
			Language.Chinese => "zh",
			Language.Korean => "ko",
			Language.Arabic => "ar",
			Language.Turkish => "tr",
			Language.Norwegian => "no",
			Language.Swedish => "sv",
			Language.Danish => "da",
			Language.Finnish => "fi",
			Language.Czech => "cs",
			Language.Hungarian => "hu",
			Language.Polish => "pl",
			Language.Romanian => "ro",
			Language.Catalan => "ca",
			Language.Greek => "el",
			Language.Hebrew => "he",
			Language.Indonesian => "id",
			Language.Thai => "th",
			Language.Vietnamese => "vi",
			Language.Bulgarian => "bg",
			Language.Ukrainian => "uk",
			Language.Slovak => "sk",
			Language.Slovenian => "sl",
			Language.Lithuanian => "lt",
			Language.Latvian => "lv",
			Language.Estonian => "et",
			Language.Afrikaans => "af",
			Language.Basque => "eu",
			Language.Belarusian => "be",
			Language.Faroese => "fo",
			Language.Icelandic => "is",
			Language.SerboCroatian => "hr",
			Language.Hindi => "hi",
			Language.Unknown => "xx",
			_ => "xx",
		};

		public static string GetDefaultCountryCode(Language language) => language switch
		{
			Language.English => "US",
			Language.Spanish => "ES",
			Language.Portuguese => "PT",
			Language.French => "FR",
			Language.German => "DE",
			Language.Italian => "IT",
			Language.Dutch => "NL",
			Language.Russian => "RU",
			Language.Japanese => "JP",
			Language.Chinese => "CN",
			Language.Korean => "KR",
			Language.Arabic => "SA",
			Language.Turkish => "TR",
			Language.Norwegian => "NO",
			Language.Swedish => "SE",
			Language.Danish => "DK",
			Language.Finnish => "FI",
			Language.Czech => "CZ",
			Language.Hungarian => "HU",
			Language.Polish => "PL",
			Language.Romanian => "RO",
			Language.Catalan => "ES",
			Language.Greek => "GR",
			Language.Hebrew => "IL",
			Language.Indonesian => "ID",
			Language.Thai => "TH",
			Language.Vietnamese => "VN",
			Language.Bulgarian => "BG",
			Language.Ukrainian => "UA",
			Language.Slovak => "SK",
			Language.Slovenian => "SI",
			Language.Lithuanian => "LT",
			Language.Latvian => "LV",
			Language.Estonian => "EE",
			Language.Afrikaans => "ZA",
			Language.Basque => "ES",
			Language.Belarusian => "BY",
			Language.Faroese => "FO",
			Language.Icelandic => "IS",
			Language.SerboCroatian => "HR",
			Language.Hindi => "IN",
			_ => "XX",
		};
	}
}
