using UnityEngine;

namespace BlueCheese.App
{
	public static class LangUtilities
	{
		public static SystemLanguage GetSystemLanguage(string languageCode) => languageCode switch
		{
			"en" => SystemLanguage.English,
			"es" => SystemLanguage.Spanish,
			"pt" => SystemLanguage.Portuguese,
			"fr" => SystemLanguage.French,
			"de" => SystemLanguage.German,
			"it" => SystemLanguage.Italian,
			"nl" => SystemLanguage.Dutch,
			"ru" => SystemLanguage.Russian,
			"ja" => SystemLanguage.Japanese,
			"zh" => SystemLanguage.Chinese,
			"ko" => SystemLanguage.Korean,
			"ar" => SystemLanguage.Arabic,
			"tr" => SystemLanguage.Turkish,
			"no" => SystemLanguage.Norwegian,
			"sv" => SystemLanguage.Swedish,
			"da" => SystemLanguage.Danish,
			"fi" => SystemLanguage.Finnish,
			"cs" => SystemLanguage.Czech,
			"hu" => SystemLanguage.Hungarian,
			"pl" => SystemLanguage.Polish,
			"ro" => SystemLanguage.Romanian,
			"ca" => SystemLanguage.Catalan,
			"el" => SystemLanguage.Greek,
			"he" => SystemLanguage.Hebrew,
			"id" => SystemLanguage.Indonesian,
			"th" => SystemLanguage.Thai,
			"vi" => SystemLanguage.Vietnamese,
			"bg" => SystemLanguage.Bulgarian,
			"uk" => SystemLanguage.Ukrainian,
			"sk" => SystemLanguage.Slovak,
			"sl" => SystemLanguage.Slovenian,
			"lt" => SystemLanguage.Lithuanian,
			"lv" => SystemLanguage.Latvian,
			"et" => SystemLanguage.Estonian,
			"af" => SystemLanguage.Afrikaans,
			"eu" => SystemLanguage.Basque,
			"be" => SystemLanguage.Belarusian,
			"fo" => SystemLanguage.Faroese,
			"is" => SystemLanguage.Icelandic,
			"hr" => SystemLanguage.SerboCroatian,
			_ => SystemLanguage.Unknown,
		};

		public static string GetLanguageCode(SystemLanguage language) => language switch
		{
			SystemLanguage.English => "en",
			SystemLanguage.Spanish => "es",
			SystemLanguage.Portuguese => "pt",
			SystemLanguage.French => "fr",
			SystemLanguage.German => "de",
			SystemLanguage.Italian => "it",
			SystemLanguage.Dutch => "nl",
			SystemLanguage.Russian => "ru",
			SystemLanguage.Japanese => "ja",
			SystemLanguage.Chinese => "zh",
			SystemLanguage.Korean => "ko",
			SystemLanguage.Arabic => "ar",
			SystemLanguage.Turkish => "tr",
			SystemLanguage.Norwegian => "no",
			SystemLanguage.Swedish => "sv",
			SystemLanguage.Danish => "da",
			SystemLanguage.Finnish => "fi",
			SystemLanguage.Czech => "cs",
			SystemLanguage.Hungarian => "hu",
			SystemLanguage.Polish => "pl",
			SystemLanguage.Romanian => "ro",
			SystemLanguage.Catalan => "ca",
			SystemLanguage.Greek => "el",
			SystemLanguage.Hebrew => "he",
			SystemLanguage.Indonesian => "id",
			SystemLanguage.Thai => "th",
			SystemLanguage.Vietnamese => "vi",
			SystemLanguage.Bulgarian => "bg",
			SystemLanguage.Ukrainian => "uk",
			SystemLanguage.Slovak => "sk",
			SystemLanguage.Slovenian => "sl",
			SystemLanguage.Lithuanian => "lt",
			SystemLanguage.Latvian => "lv",
			SystemLanguage.Estonian => "et",
			SystemLanguage.Afrikaans => "af",
			SystemLanguage.Basque => "eu",
			SystemLanguage.Belarusian => "be",
			SystemLanguage.Faroese => "fo",
			SystemLanguage.Icelandic => "is",
			SystemLanguage.SerboCroatian => "hr",
			SystemLanguage.Hindi => "hi",
			SystemLanguage.Unknown => "xx",
			_ => "xx",
		};

		public static string GetDefaultCountryCode(SystemLanguage language) => language switch
		{
			SystemLanguage.English => "US",
			SystemLanguage.Spanish => "ES",
			SystemLanguage.Portuguese => "PT",
			SystemLanguage.French => "FR",
			SystemLanguage.German => "DE",
			SystemLanguage.Italian => "IT",
			SystemLanguage.Dutch => "NL",
			SystemLanguage.Russian => "RU",
			SystemLanguage.Japanese => "JP",
			SystemLanguage.Chinese => "CN",
			SystemLanguage.Korean => "KR",
			SystemLanguage.Arabic => "SA",
			SystemLanguage.Turkish => "TR",
			SystemLanguage.Norwegian => "NO",
			SystemLanguage.Swedish => "SE",
			SystemLanguage.Danish => "DK",
			SystemLanguage.Finnish => "FI",
			SystemLanguage.Czech => "CZ",
			SystemLanguage.Hungarian => "HU",
			SystemLanguage.Polish => "PL",
			SystemLanguage.Romanian => "RO",
			SystemLanguage.Catalan => "ES",
			SystemLanguage.Greek => "GR",
			SystemLanguage.Hebrew => "IL",
			SystemLanguage.Indonesian => "ID",
			SystemLanguage.Thai => "TH",
			SystemLanguage.Vietnamese => "VN",
			SystemLanguage.Bulgarian => "BG",
			SystemLanguage.Ukrainian => "UA",
			SystemLanguage.Slovak => "SK",
			SystemLanguage.Slovenian => "SI",
			SystemLanguage.Lithuanian => "LT",
			SystemLanguage.Latvian => "LV",
			SystemLanguage.Estonian => "EE",
			SystemLanguage.Afrikaans => "ZA",
			SystemLanguage.Basque => "ES",
			SystemLanguage.Belarusian => "BY",
			SystemLanguage.Faroese => "FO",
			SystemLanguage.Icelandic => "IS",
			SystemLanguage.SerboCroatian => "HR",
			SystemLanguage.Hindi => "IN",
			_ => "XX",
		};
	}
}
